import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialDB1740415142098 implements MigrationInterface {
    name = 'InitialDB1740415142098'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "transport_unit_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "name" character varying(80) NOT NULL, "companyId" uuid NOT NULL, CONSTRAINT "UQ_7b420ef4ab94bacd2fecb95a74c" UNIQUE ("name"), CONSTRAINT "PK_77aa2f212b87a421a31d8b3d568" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transport_units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "code" character varying(50) NOT NULL, "color" character varying(20) NOT NULL, "plate" character varying(20) NOT NULL, "mark" character varying(100) NOT NULL, "companyId" uuid NOT NULL, "transport_unit_category_id" uuid NOT NULL, CONSTRAINT "UQ_180a5587a705acbeaab1de71a28" UNIQUE ("code"), CONSTRAINT "UQ_7788197341282e4eae67eb9e457" UNIQUE ("color"), CONSTRAINT "UQ_93f531d3330708d25c76d6626c8" UNIQUE ("plate"), CONSTRAINT "UQ_0b794de6c1a97ec14bc1f77d3d7" UNIQUE ("mark"), CONSTRAINT "PK_05cfecf1c380bef25d440afcf28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "name" character varying(100) NOT NULL, "companyId" uuid NOT NULL, CONSTRAINT "UQ_2187088ab5ef2a918473cb99007" UNIQUE ("name"), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "name" character varying(80) NOT NULL, "companyId" uuid NOT NULL, CONSTRAINT "UQ_8681da666ad9699d568b3e91064" UNIQUE ("name"), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "full_name" character varying(100) NOT NULL, "companyId" uuid NOT NULL, CONSTRAINT "UQ_9527c6c569be15811f45613907a" UNIQUE ("full_name"), CONSTRAINT "PK_92ab3fb69e566d3eb0cae896047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "name" character varying(100) NOT NULL, "logisticEmail" character varying(80) NOT NULL, "securityEmail" character varying(80) NOT NULL, "rrhhEmail" character varying(80) NOT NULL, CONSTRAINT "UQ_3dacbb3eb4f095e29372ff8e131" UNIQUE ("name"), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "name" character varying(50) NOT NULL, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "user_name" character varying(20) NOT NULL, "full_name" character varying(100) NOT NULL, "email" character varying(80) NOT NULL, "phone_number" character varying(20) NOT NULL, "password" text NOT NULL, "role_id" uuid NOT NULL, "company_id" uuid NOT NULL, "department_id" uuid NOT NULL, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_17d1817f241f10a3dbafb169fd2" UNIQUE ("phone_number"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branchs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "name" character varying(80) NOT NULL, CONSTRAINT "UQ_9553b92c0e363ae6c45f4e31250" UNIQUE ("name"), CONSTRAINT "PK_c2a14f542feef68e3968ce1766c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."entry_passes_visitortypeidentification_enum" AS ENUM('DNI', 'Pasaporte')`);
        await queryRunner.query(`CREATE TABLE "entry_passes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "code" character varying(50) NOT NULL, "entryDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "observation" character varying(300) NOT NULL, "statusObservation" character varying(300) NOT NULL, "visitorName" character varying(100) NOT NULL, "visitorTypeIdentification" "public"."entry_passes_visitortypeidentification_enum" NOT NULL DEFAULT 'DNI', "visitorIdNumber" character varying(20) NOT NULL, "vehiclePlate" character varying(20) NOT NULL, "vehicleColor" character varying(20) NOT NULL, "vehicleMark" character varying(50) NOT NULL, "entryTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "exitTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_1cbcc7510e5d3eeba9e4a59f57a" UNIQUE ("code"), CONSTRAINT "PK_a0762c787f4581b0b3f5d8f9636" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "entry_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "name" character varying(80) NOT NULL, CONSTRAINT "UQ_24daafb42dbcbecf1877a693b11" UNIQUE ("name"), CONSTRAINT "PK_906493f182c8c4e1e142edac8e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exit_passes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "code" character varying(50) NOT NULL, "exitDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "observation" character varying(300) NOT NULL, "statusObservation" character varying(300) NOT NULL, "exitTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_287a9241230a544920a5d043361" UNIQUE ("code"), CONSTRAINT "PK_bb39821a8c81730f7ddf9af72c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exit_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "name" character varying(80) NOT NULL, CONSTRAINT "UQ_fd66a3e0e17601101aca9bb475d" UNIQUE ("name"), CONSTRAINT "PK_e91f3b2227a9ba99fde40bf3224" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_branch_companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" character varying, "deletedAt" TIMESTAMP WITH TIME ZONE, "deletedBy" character varying, "userId" uuid, "branchId" uuid, "companyId" uuid, CONSTRAINT "PK_a5c67c383f77cacfd2c2103dd03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "transport_unit_categories" ADD CONSTRAINT "FK_7811e47e0d5c990327504e4b35a" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transport_units" ADD CONSTRAINT "FK_4f913ff1f4f535e7f46c6b951e8" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transport_units" ADD CONSTRAINT "FK_e3553e41a952691bac44bf1702c" FOREIGN KEY ("transport_unit_category_id") REFERENCES "transport_unit_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_87fa45e3f4517658b98e5c55b9c" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_d8edd5f44c26d7451d7986c5235" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_658e386266eb3045c0fc9776dd2" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_7ae6334059289559722437bcc1c" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0921d1972cf861d568f5271cd85" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_branch_companies" ADD CONSTRAINT "FK_60146e0dc8f9e25e302d0f8137c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_branch_companies" ADD CONSTRAINT "FK_cf090ca25dac17450ff76e4a574" FOREIGN KEY ("branchId") REFERENCES "branchs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_branch_companies" ADD CONSTRAINT "FK_d4bd292b3d9c3f7bcb88ffa96a7" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_branch_companies" DROP CONSTRAINT "FK_d4bd292b3d9c3f7bcb88ffa96a7"`);
        await queryRunner.query(`ALTER TABLE "user_branch_companies" DROP CONSTRAINT "FK_cf090ca25dac17450ff76e4a574"`);
        await queryRunner.query(`ALTER TABLE "user_branch_companies" DROP CONSTRAINT "FK_60146e0dc8f9e25e302d0f8137c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0921d1972cf861d568f5271cd85"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_7ae6334059289559722437bcc1c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_658e386266eb3045c0fc9776dd2"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_d8edd5f44c26d7451d7986c5235"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_87fa45e3f4517658b98e5c55b9c"`);
        await queryRunner.query(`ALTER TABLE "transport_units" DROP CONSTRAINT "FK_e3553e41a952691bac44bf1702c"`);
        await queryRunner.query(`ALTER TABLE "transport_units" DROP CONSTRAINT "FK_4f913ff1f4f535e7f46c6b951e8"`);
        await queryRunner.query(`ALTER TABLE "transport_unit_categories" DROP CONSTRAINT "FK_7811e47e0d5c990327504e4b35a"`);
        await queryRunner.query(`DROP TABLE "user_branch_companies"`);
        await queryRunner.query(`DROP TABLE "exit_types"`);
        await queryRunner.query(`DROP TABLE "exit_passes"`);
        await queryRunner.query(`DROP TABLE "entry_types"`);
        await queryRunner.query(`DROP TABLE "entry_passes"`);
        await queryRunner.query(`DROP TYPE "public"."entry_passes_visitortypeidentification_enum"`);
        await queryRunner.query(`DROP TABLE "branchs"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP TABLE "drivers"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "transport_units"`);
        await queryRunner.query(`DROP TABLE "transport_unit_categories"`);
    }

}
